theme: jekyll-theme-minimal
title: Projects
Description: This repository is a showcase of my extensive experience in advanced data analytics, data engineering, machine learning, and the latest trends in Generative AI. It includes a diverse range of projects that I have worked on, including in-depth data analysis, computer vision, natural language processing (NLP), and A/B testing. Each project reflects my proficiency in leveraging data to drive actionable insights, optimizing machine learning models, and implementing cutting-edge AI techniques.
logo: profile_pic.jpeg
show_downloads: true
footer-links:
  email: abebaw.eshe@gmail.com
  github: abe2g
  linkedin: www.linkedin.com/in/abebawu-eshetu